enum NOTIFICATIONS_PATHS {
  CREATE_NOTIFICATION = '/',
  GET_NOTIFICATIONS_BY_FILTERS = '/',
  GET_NOTIFICATION_BY_ID = '/:id',
  GET_NOTIFICATIONS_OF_RECIPIENTS = '/recipient/:recipientId',
  EDIT_NOTIFICATION = '/',
  REMOVE_NOTIFICATION = '/'
}

export {
  NOTIFICATIONS_PATHS
}
