enum PLAYER_ACTION_TYPES {
  PLAY = 'PLAY',
  RESUME = 'RESUME',
  PAUSE = 'PAUSE',
  STOP = 'STOP',
  SEEK = 'SEEK',
  SKIP_BACK = 'SKIP_BACK',
  SKIP_FORWARD = 'SKIP_FORWARD',
  SHUFFLE = 'SHUFFLE',
  REPEAT = 'REPEAT',
  SETUP = 'SETUP',
}

export {
  PLAYER_ACTION_TYPES,
};
