enum PLAYER_COMMIT_TYPES {
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED',
  STOPPED = 'STOPPED',
  CHANGE_CURRENT_DURATION = 'CHANGE_CURRENT_DURATION',
  SHUFFLE = 'SHUFFLE',
  REPEAT = 'REPEAT',
  WAITING = 'WAITING',
  STOP_WAITING = 'STOP_WAITING',
  SETUP = 'SETUP',
}

export {
  PLAYER_COMMIT_TYPES,
};
